Set-Location -Path "$PSScriptRoot"
$summaryPath = "FEATURE_SUMMARY.md"
"# Feature Summary Report" | Set-Content -Path $summaryPath -Encoding UTF8
"" | Add-Content -Path $summaryPath
"This document lists all 40 features with links to their respective text, PowerPoint, and Word documentation files." | Add-Content -Path $summaryPath
"" | Add-Content -Path $summaryPath
"---" | Add-Content -Path $summaryPath
"" | Add-Content -Path $summaryPath
"## Feature Links" | Add-Content -Path $summaryPath
"" | Add-Content -Path $summaryPath
for ($i = 1; $i -le 40; $i++) {
    $txt = "feature_$i.txt"
    $ppt = "feature_$i.pptx"
    $doc = "feature_$i.docx"
    $line = "- Feature $i: [TXT]($txt) | [PPT]($ppt) | [DOC]($doc)"
    $line | Add-Content -Path $summaryPath -Encoding UTF8
}
"" | Add-Content -Path $summaryPath
"---" | Add-Content -Path $summaryPath
"" | Add-Content -Path $summaryPath
"*Generated by Antigravity.*" | Add-Content -Path $summaryPath
